### ISSUE TITLE
hoodie child process keeps running on Grunt error

### ISSUE THREAD

**Issue by ro-ka** [hoodiehq-archive/grunt-hoodie#1]
When there is an error in another Grunt task the hoodie process keeps running in the background. This is especially a problem as the ports are still in use on next startup.

**Comment by addyosmani** [comment]
Is the solution to this killing the hoodie process to free up the ports on grunt task error?. 

Right now, Grunt doesn't support core events. They've been getting asked for them for a while but it'll take time before a decision is made there. If the above is indeed the issue you could override the fail methods to get yourself a callback in place.

**Comment by ro-ka** [comment]
I think killing the process should do the trick. But as I can kill the process by hand I'll wait for support in Grunt.

**Comment by gr2m** [comment]
@addyosmani @ro-ka any update on this?

> Is the solution to this killing the hoodie process to free up the ports on grunt task error?.
> 
> Right now, Grunt doesn't support core events. They've been getting asked for them for a while but it'll take time before a decision is made there. If the above is indeed the issue you could override the fail methods to get yourself a callback in place.

Would be really great to have that fixed!

**Comment by ro-ka** [comment]
Not sure about support in Grunt. @addyosmani: Is that implemented already? Or near implementation?

**Comment by addyosmani** [comment]
Afaik, this is something that's lined up for the 0.5 milestone but hasn't been implemented just yet. I'll double check!

**Comment by svnlto** [comment]
`hoodie-server` does now expose a `PID` which means if you need to cleanup on `['SIGTERM', 'SIGINT', 'SIGHUP', 'SIGQUIT', 'exit']` you can just listen to those events and kill the process.

Here's an example how we handle the PID internally. 

https://github.com/hoodiehq/hoodie-cli/blob/master/lib/hoodie/start.js#L118

hth

**Comment by svnlto** [comment]
I think this question has been somewhat answered by https://github.com/ro-ka/grunt-hoodie/pull/8
