### ISSUE TITLE
Show hoodie output in console

### ISSUE THREAD

**Issue by ro-ka** [hoodiehq-archive/grunt-hoodie#2]
Except for errors there is no output visible in the console. Print out the startup information of hoodie.

Bonus: Allow password input on first startup.

**Comment by boennemann** [comment]
Can be closed. Setting `childProcessOptions: {silent: false}`(or leaving it out entirely) outputs all the hoodie logs.
Setting the password for first startup is done via environment variables.

``` js
var env = process.env;
env.HOODIE_SETUP_PASSWORD = '12345';

// …

childProcessOptions: {
  env: env
}
```

**Comment by ro-ka** [comment]
:+1:
