### ISSUE TITLE
cannot get the /_api proxy working

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/grunt-hoodie#3]
Hey Robert,

I try to get the proxy working as you use it for grunt-hoodie, but it doesn't work. 

the `connect` config in my Gruntfile.js looks like this:

``` js
    // grunt server settings
    connect: {
      options: {
        port: 9000,

        // '0.0.0.0' allows for access from outside
        // 'localhost' prevents access from outside
        hostname: '0.0.0.0'
      },
      proxies: [
        {
          context: '/_api',
          host: 'localhost',
          port: 6040,
          https: false,
          changeOrigin: false
        }
      ],
      livereload: {
        options: {
          middleware: function (connect) {
            return [
              livereloadSnippet,
              mountFolder(connect, '.tmp'),
              mountFolder(connect, 'app')
            ];
          }
        }
      },
      test: {
        options: {
          middleware: function (connect) {
            return [
              mountFolder(connect, '.tmp'),
              mountFolder(connect, 'test')
            ];
          }
        }
      },
```

I've simply hardcoded the port number `6040` which is correct, hoodie is running on this port and `localhost:6040/_api' works. I start`grunt server`but then get a 404 at`localhost:9000/_api`.

Did I misunderstood something?

**Comment by ro-ka** [comment]
Looks like a problem in the proxy. I use [grunt-connect-proxy](https://npmjs.org/package/grunt-connect-proxy). Is that configured correctly?

**Comment by gr2m** [comment]
do I need it in addition to grunt-hoodie? You don't mention it in the readme

**Comment by ro-ka** [comment]
Ahm, yes, you'll need that in addition. I'll update the readme.

Does it work with the proxy added?

**Comment by gr2m** [comment]
Yeah, that works now, I forgot to add the `configureProxies` task to the `server` task. Now trying to get the the `hoodie` task to work. At the moment, it simply ends without showing any errors.

**Comment by ro-ka** [comment]
Great!

Just merged your PR. Will publish to npm in a minute.  :)
