### ISSUE TITLE
hide the Waiting for CouchDB spinner

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/grunt-hoodie#5]
When I start Hoodie with `grunt hoodie`, it shows the typical spinner, but instead of getting rewritten in-place, it ends up looking something like this

```
Initializing...
CouchDB started: http://127.0.0.1:6042
Waiting for CouchDB [-*----] 20s Waiting for CouchDB [--*---] 20s Waiting for CouchDB [---*--] 20s Waiting for CouchDB [----*-] SUCCESS 
```

There is a `config.boring` setting that shows a simple `Waiting for CouchDB...` instead, but I couldn't figure out how to set that configuration, see https://github.com/hoodiehq/hoodie-server/blob/master/lib/couch.js#L119

Sorry I can't help better, I really couldn't figure out how to fix this myself

**Comment by ro-ka** [comment]
No problem! :)

How do you pass the `config.boring` on hoodie startup? Hoodie gets started here: https://github.com/ro-ka/grunt-hoodie/blob/master/tasks/hoodie.js#L58

**Comment by gr2m** [comment]
That's a very good question, I couldn't figure it out myself :)

**Comment by svnlto** [comment]
http://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

Try: 

``` js
var hoodieProcess = exec('hoodie start', ['whatever-your-options-is-called'], function(error, stdout, stderr) {});
```

**Comment by ro-ka** [comment]
Hehe, would be good to know!  :)

**Comment by svnlto** [comment]
I think I've mentioned this previously, I really think it'd be better to use 'fork' instead of 'exec'.

See here, https://github.com/hoodiehq/hoodie-cli/blob/master/lib/hoodie/start.js#L85

@ro-ka if you could go down that route I would love to get rid of stack.json as we can expose all the data you need through the process itself. See: https://github.com/hoodiehq/hoodie-server/blob/master/lib/utils.js#L101

**Comment by ro-ka** [comment]
Have to take a look at that later. Didn't use fork before. Getting rid of stack.json would be great.

**Comment by svnlto** [comment]
fixed this in my PR

**Comment by ro-ka** [comment]
So I'm closing this.
